Expose qualityData, add qualityAcceptable function.
zmthy/http-media pull request #45
Opened 2023-07-27 12:21 UTC by kfigiela

In our circumstances it's necessary to access "raw" list of qualities instead of using existing machinery to do matching. This has not been possible, since Quality is an opaque type with no field accessors exported. In this PR I expose `qualityData` field accessor.

Furthermore, RFC explicitly adds quality of 0 meaning of being not acceptable. Added a function to test for this.

2023-07-30 22:33 UTC, zmthy commented
What are the circumstances where you need this functionality? There shouldn't be anything you need to do that's not handled by `matchQuality`, so I'd like to understand your use case.

2023-07-31 09:34 UTC, kfigiela commented
I am essentially using the library only to parse headers. My use case is to collect "raw" list of accepted languages ordered by preference (later to be used for analytics). I don't do any matching.

2023-08-01 00:22 UTC, zmthy requested changes
Use case makes sense, here's a couple of changes I'd like to see before merging.

2023-08-01 00:22 UTC, zmthy commented on CHANGES.md
> +  Exposed qualityData accessor.
There should be an empty line between the header and the text.

2023-08-01 00:22 UTC, zmthy commented on src/Network/HTTP/Media.hs
> +    , Quality(qualityData)
Formatting: a space between the type and the opening parentheses.

2023-08-01 00:22 UTC, zmthy commented on src/Network/HTTP/Media/Quality.hs
> +qualityAcceptable :: QualityOrder -> Bool
This function should be defined on `Quality`, not `QualityOrder`. `QualityOrder` only exists for the `Ord` instance.

It can also be called `isAcceptable`. I'd like to see it used in `matchQuality` instead of `q /= 0` now that it's available.

2023-08-21 17:07 UTC, kfigiela commented
@zmthy Thanks for leaving the review remarks. I'm hoping to address your comments this week.

2023-08-27 06:43 UTC, zmthy approved these changes

2023-08-27 06:45 UTC, merged

2023-09-02 03:24 UTC, zmthy commented
This is now published as [v0.8.1.0](https://hackage.haskell.org/package/http-media-0.8.1.0).